WIP: Design review remediations
18F/18f.gsa.gov pull request #3380
Opened 2021-03-11 15:45 UTC by lauraGgit

2021-03-12 22:33 UTC, igorkorenfeld commented on _sass/_uswds-theme-custom-styles.scss
> +      color: color('secondary');
@lauraGgit flagging this one since I think you said you care about the indents

2021-03-12 22:35 UTC, igorkorenfeld requested changes
Looking good, only see two things
1. The space after the intro hero should be 5 units, which will be addressed via a global change
2. The intro text (the first paragraph below the intro-hero), we should make `lg` on all pages now.

2021-03-12 23:14 UTC, lauraGgit commented on _sass/_uswds-theme-custom-styles.scss
> +      color: color('secondary');
good flag!

2021-03-12 23:18 UTC, lauraGgit commented
ok @igorkorenfeld pushed up a couple of hound fixes and made the intro text large.

#3386 has the global change so if you don't mind me holding off then i won't have to undo some conflicts

2021-03-15 14:28 UTC, igorkorenfeld approved these changes
That sounds good, I'll look double check it once we merge that one in then. In that case, everything looks good to me!

I'll let you merge this in because you have a better sense of the branches and where this goes than I do.

2021-03-15 14:34 UTC, merged