Adds required privacy policy link in footer
18F/18f.gsa.gov pull request #3589
Opened 2022-06-15 22:54 UTC by brentryanjohnson

- Adds required privacy policy link in footer
- Formats footer links for consistency

2022-06-22 15:12 UTC, igorkorenfeld requested changes
In the Federalist preview it seems like the identifier links all return to the current page(that is are null) instead of linking out. I am guessing it's a variable or file naming issue  (`identifier` vs `anchor`) but would need to dig a little further

2022-06-22 15:12 UTC, igorkorenfeld commented on _data/usa_anchor.yml
> +      privacy_policy-url: https://www.gsa.gov/website-information/website-policies
Minor nitpick, but to be consistent with the other links (and guides) could you make the dash an underscore (i.e. `privacy_policy_url`

2022-06-22 15:12 UTC, igorkorenfeld commented on _includes/footer.html
> +          <a class="usa-identifier__required-link usa-link" href="{{ identifier.privacy_policy-url }}" title="Our privacy policy">
Same here,  could you make the dash an underscore (`privacy_policy_url`)

2022-06-22 15:12 UTC, igorkorenfeld commented on _includes/footer.html
>      <div class="usa-identifier__container">
I think it may make sense to pull the identifier into its own component and `include` it in the footer.

2022-06-22 15:12 UTC, igorkorenfeld commented on _data/usa_anchor.yml
>        no_fear_act_url: "https://www.gsa.gov/about-us/organization/office-of-civil-rights/notification-and-federal-employee-antidiscrimination-and-retaliation-act-of-2002"
Should probably rename this file to `usa_identifier` to match the new name

2022-08-11 17:24 UTC, Sgtpluck commented
Closing this, it was addressed here: https://github.com/18F/18f.gsa.gov/pull/3604

2022-08-11 17:24 UTC, closed without merging