add author laura-nash
18F/18f.gsa.gov pull request #3682
Opened 2023-05-01 20:39 UTC by MelissaBraxton

# Pull request summary
This PR adds Laura Nash as an author so they can be added to this post: #3677 

(Optional) Closes #(issue_number).

## Reminder - please do the following before assigning reviewer

- [ ] update readme
- [ ] For frontend changes, ensure design review

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introdcued

2023-05-01 20:44 UTC, lauraGgit requested changes

2023-05-01 20:44 UTC, lauraGgit commented on _authors/laura-nash.md
> +full_name: Laura-Nash
I think you want full name to be `full_name: Laura Nash`

2023-05-01 21:11 UTC, MelissaBraxton commented
Fixed!

2023-05-02 00:15 UTC, geekygirlsarah approved these changes

2023-05-02 00:16 UTC, geekygirlsarah commented
The build failures are because other authors are missing. This can be merged in as-is and I'll make another PR to add the other authors.

2023-05-02 00:16 UTC, merged