Tlc footer order
18F/18f.gsa.gov pull request #3712
Opened 2023-07-17 20:40 UTC by AnitaYCheng

# Pull request summary
Fixes #3709 by removing all CSS order properties manually set in the home template.

## Reminder - please do the following before assigning reviewer

- [ ] update readme
- [ ] For frontend changes, ensure design review

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introduced

2023-07-17 22:10 UTC, igorkorenfeld requested changes
The styleguide page is looking good! But taking out the order introduces a new issue in that it resets the contents of the hero which makes a more awkward layout on smaller screens. 

It seems like you could just remove the `unset` from the `footer` and still have it work without removing the ordering on the hero. Or if you do want to remove those rules, then perhaps we could rethink how hero is implemented. 

I will note that adding `unset` fixed the bad ordering on the `footer` [here](https://github.com/18F/18f.gsa.gov/pull/3695). However, it seems like since then there have been other changes that also impact the ordering and which may make `unset` unnecessary.

2023-07-17 22:14 UTC, jskinne3 approved these changes
I note that this PR preserves functionality that I've touched in the past, namely:
1. footer elements stay in the correct order at various page widths, and
2. tab key navigation of links goes in the correct order

2023-07-18 18:12 UTC, AnitaYCheng commented
> The styleguide page is looking good! But taking out the order introduces a new issue in that it resets the contents of the hero which makes a more awkward layout on smaller screens.
> 
> It seems like you could just remove the `unset` from the `footer` and still have it work without removing the ordering on the hero. Or if you do want to remove those rules, then perhaps we could rethink how hero is implemented.
> 
> I will note that adding `unset` fixed the bad ordering on the `footer` [here](https://github.com/18F/18f.gsa.gov/pull/3695). However, it seems like since then there have been other changes that also impact the ordering and which may make `unset` unnecessary.

I added back the CSS order properties to the homepage and tested keyboard navigation in the footer. It should be good now! @igorkorenfeld

2023-07-18 19:42 UTC, igorkorenfeld approved these changes
Minor note about the style, other than that looks good! Thanks for making the updates.

2023-07-18 19:42 UTC, igorkorenfeld commented on _sass/_templates/home.scss
> +    order:4;
To follow a consistent style there should be a space after the colon on each of these.

2023-07-18 19:42 UTC, igorkorenfeld commented on _sass/_uswds-theme-custom-styles.scss
> +  padding-bottom:2em;
And here

2023-07-18 19:42 UTC, igorkorenfeld commented on _sass/_templates/home.scss
> +    order:2;
Same here

2023-07-21 16:29 UTC, merged