Update tax-court.md
18F/18f.gsa.gov pull request #3726
Opened 2023-08-02 00:28 UTC by ameliaswong

Revise case study to reflect new structure

# Pull request summary

(Optional) Closes #(issue_number).

## Reminder - please do the following before assigning reviewer

- [ ] update readme
- [x] For frontend changes, ensure design review

And make sure that automated checks are ok

- fix houndci feedback
- ensure tests pass
- federalist builds
- no new SNYK vulnerabilities are introdcued

2023-08-02 00:36 UTC, ameliaswong commented
[Preview link](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/taxcourt-casestudy-update/our-work/tax-court/)

2023-08-02 17:34 UTC, durland18F requested changes
Hey, I hate to say it because I don't like this convention, but we follow AP in that we put a space on each side of an em dash. Please make that change. Thanks!

2023-08-02 17:36 UTC, ameliaswong commented
@durland18F No worries! Chicago is what I've typically worked with so need to get familiar with AP. (Will add it to my task list.) Making the change now.

2023-08-08 20:22 UTC, quarterback approved these changes

2023-08-08 20:23 UTC, merged