Add blog post and new author
18F/18f.gsa.gov pull request #3810
Opened 2024-03-04 17:49 UTC by juliaklindpaintner

# Pull request summary

- Adds @amandarkennedy as an author
- Adds blog post "Customer experience: beyond surveys"

2024-03-04 21:23 UTC, jskinne3 requested changes
Suggest removing a stray `-` character

I'm trying to figure out why the preview build isn't working

2024-03-04 21:27 UTC, juliaklindpaintner commented on _posts/2024-03-05-customer-experience-beyond-surveys.md
> +-
Ah thank you for catching! I meant to add a third tag. Added now!

2024-03-04 22:59 UTC, jskinne3 approved these changes
Great!

2024-03-05 13:42 UTC, juliaklindpaintner commented
@amandarkennedy Can you take a look at [this preview of the post](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/cx-beyond-surveys-amanda-kennedy/2024/03/05/customer-experience-beyond-surveys/) and see if you're happy with it? @quarterback is OOO today, but I will merge to publish — just wanted to get another set of eyes on it first.

2024-03-05 14:25 UTC, amandarkennedy commented
@juliaklindpaintner the only thing I noticed is that the following methods-related headers are now h1 when they were just bolded normal text in the draft. At the very least, I would prefer they be h2, but otherwise looks good. 
<img width="521" alt="Screenshot 2024-03-05 at 9 24 25 AM" src="https://github.com/18F/18f.gsa.gov/assets/121978626/c1e229b6-b1bb-4af5-8a06-aeb90c3f5d43">

2024-03-05 14:30 UTC, juliaklindpaintner commented
@amandarkennedy They are actually h2s already (the other headings are h1), but let me adjust to make them just be bolded.

2024-03-05 14:32 UTC, amandarkennedy commented
@juliaklindpaintner that would be great, thanks!

2024-03-05 14:35 UTC, juliaklindpaintner commented
@amandarkennedy How about [this](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/cx-beyond-surveys-amanda-kennedy/2024/03/05/customer-experience-beyond-surveys/)?

2024-03-05 14:42 UTC, amandarkennedy commented
@juliaklindpaintner this looks great! One more thing I just realized: "Choose your method" doesn't follow the same framing of the other headers in the form of a question. Would it be possible to change it to "What method should you choose?" I am happy to do that (or leave as is).

2024-03-05 14:46 UTC, juliaklindpaintner commented
I see what you're saying @amandarkennedy. The last heading is also a different format ("Implement") — are you okay with that one?

2024-03-05 14:47 UTC, amandarkennedy commented
@juliaklindpaintner good question, and yes! I am okay with keeping `Implement` as is. Thanks for checking!

2024-03-05 15:01 UTC, juliaklindpaintner commented
Okay! One last check of [this preview](https://federalist-c58f58dc-a215-4616-a54c-12b5eb011096.sites.pages.cloud.gov/preview/18f/18f.gsa.gov/cx-beyond-surveys-amanda-kennedy/2024/03/05/customer-experience-beyond-surveys/)? If it looks good, you can go ahead and approve this PR :)

2024-03-05 15:04 UTC, merged

2024-03-05 15:28 UTC, quarterback commented
I'm around. and it looks good