Add Speaker bureau page
18F/18f.gsa.gov pull request #4056
Opened 2024-08-12 23:02 UTC by AnitaYCheng

# Pull request summary
Add speaker bureau page, including a new image.

2024-08-12 23:33 UTC, AnitaYCheng commented
New page is added and the image works! The `{{ site.baseurl }}` stuff and callout boxes are still broken, but I checked and they're also broken on the `replatform-main` branch build, so I won't worry too much about it. 🙂

2024-08-13 15:03 UTC, beechnut requested changes
Hi @AnitaYCheng, I've left some technical changes and suggestions for content changes. I tried to differentiate tech changes from content by adding `(content)` anywhere it's a content change.

Let me know if you want help rebasing or doing anything else, happy to hop on a call.

2024-08-13 15:03 UTC, beechnut commented on content/pages/contact/speaker-bureau.md
> +permalink: /speaker-bureau/
concern (content): Are people familiar with the term "speaker bureau"? That's new to me.

change (content, suggested, non-blocking): Change the `permalink` to /speakers/

change (content, suggested, non-blocking): Change the `title` to something like "Have 18F speak at your event"

2024-09-24 21:14 UTC, AnitaYCheng commented
Update: I waited until the Eleventy replatform was done and redid this work in #4075 .

2024-09-24 21:14 UTC, closed without merging